// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBe52GfnTAAwE_wGHU3K-8cZxs-Kfdbnxs',
    appId: '1:188672168084:web:738c6e2f0130ac284de481',
    messagingSenderId: '188672168084',
    projectId: 'ouabootcamp-fb5bc',
    authDomain: 'ouabootcamp-fb5bc.firebaseapp.com',
    storageBucket: 'ouabootcamp-fb5bc.appspot.com',
    measurementId: 'G-95L0P0QNH9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBv8KZewDmP4ePfwg42AwFmmwwtUo_aioA',
    appId: '1:188672168084:android:8ddf10e4b420d2654de481',
    messagingSenderId: '188672168084',
    projectId: 'ouabootcamp-fb5bc',
    storageBucket: 'ouabootcamp-fb5bc.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDNTgvednqLwzPRIZ2IzuOX5aSfy6n_31g',
    appId: '1:188672168084:ios:d3984f0955ef90b44de481',
    messagingSenderId: '188672168084',
    projectId: 'ouabootcamp-fb5bc',
    storageBucket: 'ouabootcamp-fb5bc.appspot.com',
    iosBundleId: 'com.example.ouabootcamp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDNTgvednqLwzPRIZ2IzuOX5aSfy6n_31g',
    appId: '1:188672168084:ios:d3984f0955ef90b44de481',
    messagingSenderId: '188672168084',
    projectId: 'ouabootcamp-fb5bc',
    storageBucket: 'ouabootcamp-fb5bc.appspot.com',
    iosBundleId: 'com.example.ouabootcamp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBe52GfnTAAwE_wGHU3K-8cZxs-Kfdbnxs',
    appId: '1:188672168084:web:ec390caac8007c714de481',
    messagingSenderId: '188672168084',
    projectId: 'ouabootcamp-fb5bc',
    authDomain: 'ouabootcamp-fb5bc.firebaseapp.com',
    storageBucket: 'ouabootcamp-fb5bc.appspot.com',
    measurementId: 'G-D32TE1D86Q',
  );
}
